version: '3.8'

services:
  user_ticket:
    container_name: user_ticket
    build: 
      context: ../services/user_ticket
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - IAM_URL=${IAM_URL}
      - SECRET=${SECRET}
      - MANAGE_SERVICES_URL=${MANAGE_SERVICES_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_ticket.rule=Host(`userticket.localhost`)"
      - "traefik.http.routers.user_ticket.entrypoints=web"
      - "traefik.http.services.user_ticket.loadbalancer.server.port=8000"
    networks:
      - app-network 
    depends_on:
      postgres_container:
        condition: service_healthy
      
    restart: unless-stopped
        
  postgres_container:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yourusername"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - app-network
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres_container:
        condition: service_healthy
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 
volumes:
  postgres_data: