from enum import Enum
from pydantic import BaseModel
from datetime import date, time
    
class BusCreate(BaseModel):
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    capacity: int

class AirplainCreate(BaseModel):
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    capacity: int

class TourCreate(BaseModel):
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    end_date: date
    end_time: time
    capacity: int

class TrainCreate(BaseModel):
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    compartment_num: int
    compart_person_num: int

class BusResponse(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    capacity: int
    remain: int

class AirplainResponse(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    capacity: int
    remain: int

class TourResponse(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    end_date: date
    end_time: time
    capacity: int
    remain: int

class TrainResponse(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    compartment_num: int
    compart_person_num: int
    remain: int

class BusResponse2(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    capacity: int

class AirplainResponse2(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    capacity: int

class TourResponse2(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    end_date: date
    end_time: time
    capacity: int

class TrainResponse2(BaseModel):
    id: int
    company_id: int
    from_location: str
    to_location: str
    start_date: date
    start_time: time
    detail: str
    vehicle_type: str
    vehicle_num: int
    price: int
    is_canceled: bool
    compartment_num: int
    compart_person_num: int

class FilterService(BaseModel):
    from_location: str
    to_location: str
    start_date: date

class GetInfo(BaseModel):
    id: int
    service_type: str